version: "3.8"
services:
  frontend:
    container_name: frontend-spa
    build:
      context: .
    restart: always
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4001:4001"
    command: npm run dev -- --host 0.0.0.0

networks:
  default:
    name: external-network
    external: true
